app/models/user.py
# Importing necessary modules
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from hashlib import md5
import jwt
from datetime import datetime, timezone
from time import time
import sqlalchemy as sa
from flask import current_app
from app import db
from app import login
from app.models import product

# User model class definition
class User(UserMixin, db.Model):
    # Database columns
    id = sa.Column(sa.Integer, primary_key=True)
    username = sa.Column(sa.String(64), index=True, unique=True)
    name = sa.Column(sa.String(64), index=False)
    email = sa.Column(sa.String(120), index=True, unique=True)
    password_hash = sa.Column(sa.String(256))
    status = sa.Column(sa.String(20), index=True)
    about_me = sa.Column(sa.String(140))
    money = sa.Column(sa.Integer(), default=100)
    last_seen = sa.Column(sa.DateTime, default=lambda: datetime.now(timezone.utc))

    # User representation
    def __repr__(self):
        return '<User {}>'.format(self.username)

    # User loader for Flask-Login
    @login.user_loader
    def load_user(id):
        return db.session.get(User, int(id))

    # Method to set password hash
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    # Method to check password hash
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    # Method to generate avatar URL using Gravatar
    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return f'https://www.gravatar.com/avatar/{digest}?d=identicon&s={size}'

    # Method to generate a reset password token
    def get_reset_password_token(self, expires_in=600):
        return jwt.encode(
            {'reset_password': self.id, 'exp': time() + expires_in},
            current_app.config['SECRET_KEY'], algorithm='HS256')

    # Method to verify a reset password token
    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, current_app.config['SECRET_KEY'],
                            algorithms=['HS256'])['reset_password']
        except:
            return
        return db.session.get(User, id)

    # Method to get the count of images uploaded by the user
    def get_image_count(self, user_id):
        image_count = product.Product.query.filter_by(seller_id=user_id).count()
        return image_count

    # Method to get the count of purchases made by the user
    def get_purchase_count(self, user_id):
        purchase_count = product.Product.query.filter_by(buyer_id=user_id).count()
        return purchase_count

# Function to get the count of users
def user_count():
    return User.query.count()

app/users/forms.py
"""
This module defines a FlaskForm for editing user profiles.

The EditProfileForm class defines a form with fields for editing a user's username and about me section.
It also includes validation logic to ensure unique usernames.

Classes:
    EditProfileForm: A FlaskForm for editing user profiles.

Attributes:
    username: StringField - Field for entering the new username.
    about_me: TextAreaField - Field for entering information about the user.
    submit: SubmitField - Button for submitting the form.

Methods:
    __init__: Initializes the EditProfileForm instance.
    validate_username: Validates the uniqueness of the entered username.
"""

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length

import sqlalchemy as sa
from app import db
from app.models.user import User

class EditProfileForm(FlaskForm):
    """
    A form for editing user profiles.
    """

    username = StringField('Username', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=140)])
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        """
        Initialize the EditProfileForm instance.

        Args:
            original_username (str): The original username of the current user.
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        super().__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        """
        Validate the uniqueness of the entered username.

        Args:
            username (str): The username to validate.

        Raises:
            ValidationError: If the entered username is not unique.
        """
        if username.data != self.original_username:
            user = db.session.scalar(sa.select(User).where(User.username == self.username.data))
            if user is not None:
                raise ValidationError('Please use a different username.')

app/users/__init__.py
# Importing Flask Blueprint module
from flask import Blueprint

# Creating a Blueprint instance for the users module
bp = Blueprint('users', __name__)

# Import and register routes for user-related functionality
from app.users import routes

app/users/routes.py
from flask import render_template, flash, redirect, url_for, request
from urllib.parse import urlsplit
from datetime import datetime, timezone
import sqlalchemy as sa

# Import Flask related modules
from app import db
from app.models.user import User
from app.models.reward import Reward
from app.users import bp
from flask_login import current_user, login_user, logout_user, login_required
from app.users.forms import EditProfileForm

@bp.before_request
def before_request():
    """
    Update the last_seen timestamp of the current user before each request.
    """
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now(timezone.utc)
        db.session.commit()

@bp.route('/user/<username>')
@login_required
def user(username):
    """
    Render the user profile page.

    Args:
        username (str): The username of the user whose profile is being viewed.

    Returns:
        render_template: The rendered HTML template.
    """
    user = db.first_or_404(sa.select(User).where(User.username == username))

    # Get user-specific information
    image_count = user.get_image_count(user.id)
    purchase_count = user.get_purchase_count(user.id)

    # Redirect if the user is not the current user
    if user.id != current_user.id:
        flash('You are not allowed to access that location.')
        return redirect(url_for('main.index'))

    # Get recent rewards of the user
    recent_rewards = Reward.query.filter_by(user_id=user.id).order_by(Reward.timestamp.desc()).limit(20).all()

    return render_template('users/user.html', user=user, image_count=image_count, purchase_count=purchase_count, recent_rewards=recent_rewards)

@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    """
    Render the edit profile page and handle form submission.

    Returns:
        render_template: The rendered HTML template.
    """
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        # Update the user's profile information
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('users.user', username=current_user.username))
    elif request.method == 'GET':
        # Populate the form with the current user's information
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('users/edit_profile.html', title='Edit Profile', form=form)

app/templates/users/edit_profile.html
{% extends "base.html" %}

{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col col-lg-6 area">
            <h1>Edit Profile</h1>
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/users/user.html
{% extends "base.html" %}

{% block content %}
    <!-- Display content for the user profile page. -->
    <section id="profile" class="xh-100 gradient-custom-2">
        <div class="container py-5 xh-100" style="padding-top: 1rem!important">
            <div class="row d-flex justify-content-center align-items-center xh-100x">
                <div class="col col-lg-12 col-xl-12 area">
                    <div class="card-none">
                        <div class="rounded-top-none text-white d-flex flex-row profile-bg1">
                            <!-- User profile image and edit profile link -->
                            <div class="ms-4 mt-5 d-flex flex-column text-center" style="width: 150px;">
                                <img src="{{ user.avatar(150) }}"
                                     alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2 avatar"
                                     style="width: 150px; z-index: 1">
                                <a class="mb-2" data-mdb-ripple-color="dark"
                                   style="z-index: 1;" href="{{ url_for('users.edit_profile') }}">Edit profile</a>
                            </div>
                            <!-- User name and username -->
                            <div class="ms-3" style="margin-top: 130px; color: #333;">
                                <h5>{{ user.name }}</h5>
                                <p class="username">{{ user.username }}</p>
                            </div>
                        </div>
                        <!-- User stats section -->
                        <div class="p-4 text-black profile-bg2">
                            <div class="d-flex justify-content-end text-center py-1">
                                <div>
                                    <p class="mb-1 h5">{{ image_count }}</p>
                                    <p class="small text-muted mb-0">Images</p>
                                </div>
                                <div class="px-3">
                                    <p class="mb-1 h5">{{ purchase_count }}</p>
                                    <p class="small text-muted mb-0">Purchases</p>
                                </div>
                                <div>
                                    <p class="mb-1 h5">${{ user.money }}</p>
                                    <p class="small text-muted mb-0">Money</p>
                                </div>
                            </div>
                        </div>
                        <!-- User about section -->
                        <div class="card-body-none p-4-none text-black" style="margin-top: 1.5rem">
                            <div class="mb-5">
                                <p class="lead fw-normal mb-1 text-white">About</p>
                                <div class="p-4 profile-bg2">
                                    <p class="font-italic mb-1 about-me">{% if user.about_me %}Bio: {{ user.about_me }} {% endif %}</p>
                                    <p class="font-italic mb-1">{% if user.email %} Email: {{ user.email }} {% endif %}</p>
                                    <p class="font-italic mb-0">{% if user.last_seen %} Last seen on: {{ user.last_seen }} {% endif %}</p>
                                </div>
                                <!-- Recent rewards section -->
                                <p class="lead fw-normal mb-1 text-white mt-1">Recent rewards (latest 20)</p>
                                <div class="p-4 profile-bg3">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th scope="col">Date</th>
                                                <th scope="col">Reason</th>
                                                <th scope="col">Type</th>
                                                <th scope="col">Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% if recent_rewards: %}
                                                {% for reward in recent_rewards: %}
                                                    <tr>
                                                        <td>{{ reward.timestamp.strftime('%d-%m-%Y') }}</td>
                                                        <td>{{ reward.reason }}</td>
                                                        <td>{{ reward.reward_type }}</td>
                                                        <td>{% if reward.reward_type == 'Debit' %}- {% endif %}{{ reward.amount }}</td>
                                                    </tr>
                                                {% endfor %}
                                            {% else: %}
                                                <tr>
                                                    <td colspan="4">No rewards found in the system</td>
                                                </tr>
                                            {% endif %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}